### ISSUE TITLE
Cannot configure mpich in separate build directory

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/Yggdrasil#7811]
This fails with the current HEAD of mpich:

```sh
mkdir build
cd build
../configure
```

The error message (which does not abort configure!) is
```
  --> [src/binding/fortran/use_mpi_f08/mpi_f08_types.f90]
Traceback (most recent call last):
  File "/Users/eschnett/src/mpich/build-gcc/../maint/gen_binding_f08.py", line 171, in <module>
    main()
  File "/Users/eschnett/src/mpich/build-gcc/../maint/gen_binding_f08.py", line 164, in main
    load_mpi_h_in("src/include/mpi.h.in")
  File "/Users/eschnett/src/mpich/maint/local_python/binding_f08.py", line 1680, in load_mpi_h_in
    with open(f, "r") as In:
FileNotFoundError: [Errno 2] No such file or directory: 'src/include/mpi.h.in'
```

I think there is a path prefix missing in this Python script.

Errors in this script should also abort `configure`.

**Comment by eschnett** [comment]
`gen_binding_f77.py` is probably also affected.
